Repository Refhub-ir/Refhub, pull requests merged in 2025-07, with the labels that each got.

#98 Fix
  .github/workflows/ci.yml
Labels: PR:size/S, NO JIRA

#99 Fix CI
  .github/workflows/ci.yml
Labels: PR:size/S, NO JIRA

#100 Update ci.yml
  .github/workflows/ci.yml
Labels: PR:size/M, NO JIRA

#103 Fix CI
  .github/workflows/ci.yml
Labels: PR:size/M, NO JIRA

#104 Update ci.yml (#100)
  .github/workflows/ci.yml
Labels: PR:size/M, NO JIRA

#97 Seed data
  Refhub/Data/Seed/DataSeeder.cs
  Refhub/Data/Seed/ExcelSeeder.cs
  Refhub/Migrations/20250616145440_AddAuthorTable.Designer.cs
  Refhub/Migrations/20250616145440_AddAuthorTable.cs
  Refhub/Program.cs
  Refhub/Refhub.csproj
  Refhub/SeedData/AuthorBookData.xlsx
  Refhub/SeedData/AuthorData.xlsx
  Refhub/SeedData/BookData.xlsx
  Refhub/SeedData/BookKeywordData.xlsx
  Refhub/SeedData/BookRelationData.xlsx
  Refhub/SeedData/CategoryData.xlsx
  Refhub/SeedData/KeywordData.xlsx
Labels: PR:size/XXL, NO JIRA
